framework:
    messenger:
        failure_transport: failed
        default_bus: command.bus
        buses:
            command.bus: ~
            event.bus: ~

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
                    service: null
                    delay: 1000
                    max_delay: 0

            #failed: 'doctrine://default'
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
#            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
#            Symfony\Component\Notifier\Message\ChatMessage: async
#            Symfony\Component\Notifier\Message\SmsMessage: async
            #App\Message\PurchaseConfirmmationNotification: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            'App\Message\Command\SaveOrder': sync
            'App\Message\Event\OrderSavedEvent': async

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'